/**
 * Bash completion script for the dojops CLI.
 * Exported as a string constant — printed by `dojops completion bash`.
 */
export const BASH_COMPLETION_SCRIPT = `#!/usr/bin/env bash
# dojops bash completion — generated by dojops completion bash

_dojops_get_dynamic() {
  local type="$1"
  local result
  result=$(timeout 2 dojops --get-completions "$type" 2>/dev/null) || return
  echo "$result"
}

_dojops() {
  local cur prev words cword
  _init_completion || return

  # Top-level commands
  local commands="plan generate apply validate explain debug analyze review auto inspect agents history skills modules tools toolchain scan chat check verify provider config auth serve status doctor init clean destroy rollback checkpoint trust untrust cron upgrade cost drift fix-deps runs mcp memory tokens insights help completion"

  # Subcommand maps
  local sub_debug="ci"
  local sub_analyze="diff"
  local sub_agents="list info create remove"
  local sub_history="list show verify audit repair export"
  local sub_skills="list init validate publish install search dev update export import"
  local sub_modules="list init validate publish install search dev update export import"
  local sub_tools="list init validate publish install search dev"
  local sub_toolchain="list load install remove clean"
  local sub_config="show get set delete validate reset profile"
  local sub_config_profile="create use delete list"
  local sub_auth="login status logout"
  local sub_serve="credentials"
  local sub_chat="export"
  local sub_inspect="config session"
  local sub_provider="list default add remove switch"
  local sub_cron="add list remove"
  local sub_checkpoint="create list restore clean"
  local sub_trust="list"
  local sub_completion="bash zsh fish install"

  # Global flags
  local global_flags="--verbose --debug --quiet --no-color --raw --non-interactive --dry-run --provider --model --fallback-provider --agent --skill --module --tool --file --profile --temperature --timeout --output --help --version"

  # Command-specific flags
  local flags_plan="--execute --yes --skip-verify"
  local flags_apply="--resume --yes --skip-verify --force --allow-all-paths --install-packages --replay --task --timeout --repair-attempts"
  local flags_scan="--security --deps --iac --sbom --license --fix --compare --target --fail-on --compliance"
  local flags_drift="--terraform --kubernetes --path"
  local flags_fixdeps="--npm --pip --dry-run"
  local flags_serve="--port --no-auth --tls-cert --tls-key"
  local flags_chat="--session --resume --agent --message"
  local flags_auto="--skip-verify --force --allow-all-paths --repair-attempts --commit"

  # Determine command context
  local cmd="" subcmd="" pos=1
  while [[ $pos -lt $cword ]]; do
    local word="\${words[$pos]}"
    if [[ "$word" != -* ]]; then
      if [[ -z "$cmd" ]]; then
        cmd="$word"
      elif [[ -z "$subcmd" ]]; then
        subcmd="$word"
      fi
    fi
    ((pos++))
  done

  # After --, stop completing flags
  local saw_dashdash=0
  for ((i=1; i < cword; i++)); do
    if [[ "\${words[$i]}" == "--" ]]; then
      saw_dashdash=1
      break
    fi
  done

  # Dynamic value completions for specific flags
  if [[ $saw_dashdash -eq 0 ]]; then
    case "$prev" in
      --provider)
        COMPREPLY=($(compgen -W "$(_dojops_get_dynamic providers)" -- "$cur"))
        return ;;
      --agent)
        COMPREPLY=($(compgen -W "$(_dojops_get_dynamic agents)" -- "$cur"))
        return ;;
      --skill|--module|--tool)
        COMPREPLY=($(compgen -W "$(_dojops_get_dynamic skills)" -- "$cur"))
        return ;;
      --output)
        COMPREPLY=($(compgen -W "table json yaml stream-json" -- "$cur"))
        return ;;
      --fail-on)
        COMPREPLY=($(compgen -W "CRITICAL HIGH MEDIUM LOW" -- "$cur"))
        return ;;
      --file|-f)
        _filedir
        return ;;
    esac
  fi

  # No command yet — complete commands
  if [[ -z "$cmd" ]]; then
    if [[ "$cur" == -* && $saw_dashdash -eq 0 ]]; then
      COMPREPLY=($(compgen -W "$global_flags" -- "$cur"))
    else
      COMPREPLY=($(compgen -W "$commands" -- "$cur"))
    fi
    return
  fi

  # Have command, no subcommand — complete subcommands or flags
  if [[ -z "$subcmd" ]]; then
    local sub_var="sub_$cmd"
    local subs="\${!sub_var}"
    if [[ -n "$subs" && "$cur" != -* ]]; then
      COMPREPLY=($(compgen -W "$subs" -- "$cur"))
      return
    fi
  fi

  # 3-level: config profile <TAB>
  if [[ "$cmd" == "config" && "$subcmd" == "profile" && "$cur" != -* ]]; then
    COMPREPLY=($(compgen -W "$sub_config_profile" -- "$cur"))
    return
  fi

  # Flag completions
  if [[ "$cur" == -* && $saw_dashdash -eq 0 ]]; then
    local cmd_flags_var="flags_$cmd"
    local cmd_flags="\${!cmd_flags_var}"
    COMPREPLY=($(compgen -W "$cmd_flags $global_flags" -- "$cur"))
  fi
}

complete -F _dojops dojops
`;
