/**
 * Fish completion script for the dojops CLI.
 * Exported as a string constant — printed by `dojops completion fish`.
 */
export const FISH_COMPLETION_SCRIPT = `# dojops fish completion — generated by dojops completion fish

# Helper to check if a subcommand has been given
function __dojops_no_subcommand
    set -l cmd (commandline -opc)
    for word in $cmd[2..-1]
        if not string match -q -- '-*' $word
            return 1
        end
    end
    return 0
end

# Helper to check if a specific command was given
function __dojops_using_command
    set -l cmd (commandline -opc)
    set -l target $argv[1]
    for word in $cmd[2..-1]
        if not string match -q -- '-*' $word
            if test "$word" = "$target"
                return 0
            end
            return 1
        end
    end
    return 1
end

# Helper to check for command + subcommand
function __dojops_using_subcommand
    set -l cmd (commandline -opc)
    set -l target_cmd $argv[1]
    set -l target_sub $argv[2]
    set -l found_cmd 0
    for word in $cmd[2..-1]
        if not string match -q -- '-*' $word
            if test $found_cmd -eq 0
                if test "$word" = "$target_cmd"
                    set found_cmd 1
                else
                    return 1
                end
            else
                if test "$word" = "$target_sub"
                    return 0
                end
                return 1
            end
        end
    end
    return 1
end

# Dynamic completions
function __dojops_complete_providers
    dojops --get-completions providers 2>/dev/null; or true
end
function __dojops_complete_agents
    dojops --get-completions agents 2>/dev/null; or true
end
function __dojops_complete_modules
    dojops --get-completions modules 2>/dev/null; or true
end

# Disable file completions by default
complete -c dojops -f

# Top-level commands
complete -c dojops -n '__dojops_no_subcommand' -a plan -d 'Decompose goal into task graph'
complete -c dojops -n '__dojops_no_subcommand' -a generate -d 'Generate DevOps config'
complete -c dojops -n '__dojops_no_subcommand' -a apply -d 'Execute a saved plan'
complete -c dojops -n '__dojops_no_subcommand' -a validate -d 'Validate plan against schemas'
complete -c dojops -n '__dojops_no_subcommand' -a explain -d 'LLM explains a plan'
complete -c dojops -n '__dojops_no_subcommand' -a debug -d 'Debug tools'
complete -c dojops -n '__dojops_no_subcommand' -a analyze -d 'Analysis tools'
complete -c dojops -n '__dojops_no_subcommand' -a review -d 'DevSecOps review'
complete -c dojops -n '__dojops_no_subcommand' -a auto -d 'Autonomous mode with self-repair'
complete -c dojops -n '__dojops_no_subcommand' -a inspect -d 'Inspect config and session'
complete -c dojops -n '__dojops_no_subcommand' -a agents -d 'Manage specialist agents'
complete -c dojops -n '__dojops_no_subcommand' -a history -d 'View execution history'
complete -c dojops -n '__dojops_no_subcommand' -a modules -d 'Manage DevOps modules'
complete -c dojops -n '__dojops_no_subcommand' -a toolchain -d 'Manage system toolchain'
complete -c dojops -n '__dojops_no_subcommand' -a scan -d 'Security scan'
complete -c dojops -n '__dojops_no_subcommand' -a chat -d 'Interactive AI session'
complete -c dojops -n '__dojops_no_subcommand' -a check -d 'Config quality check'
complete -c dojops -n '__dojops_no_subcommand' -a verify -d 'Verify config file'
complete -c dojops -n '__dojops_no_subcommand' -a provider -d 'Manage LLM providers'
complete -c dojops -n '__dojops_no_subcommand' -a config -d 'Configure settings'
complete -c dojops -n '__dojops_no_subcommand' -a auth -d 'Authenticate'
complete -c dojops -n '__dojops_no_subcommand' -a serve -d 'Start API server'
complete -c dojops -n '__dojops_no_subcommand' -a status -d 'System health diagnostics'
complete -c dojops -n '__dojops_no_subcommand' -a init -d 'Initialize .dojops/'
complete -c dojops -n '__dojops_no_subcommand' -a clean -d 'Remove generated artifacts'
complete -c dojops -n '__dojops_no_subcommand' -a rollback -d 'Reverse an applied plan'
complete -c dojops -n '__dojops_no_subcommand' -a cron -d 'Manage scheduled jobs'
complete -c dojops -n '__dojops_no_subcommand' -a upgrade -d 'Check for CLI updates'
complete -c dojops -n '__dojops_no_subcommand' -a help -d 'Show help'
complete -c dojops -n '__dojops_no_subcommand' -a completion -d 'Generate shell completions'
complete -c dojops -n '__dojops_no_subcommand' -a tools -d 'Manage modules (deprecated)'
complete -c dojops -n '__dojops_no_subcommand' -a doctor -d 'System diagnostics (alias)'
complete -c dojops -n '__dojops_no_subcommand' -a destroy -d 'Remove artifacts (deprecated)'

# Subcommands: debug
complete -c dojops -n '__dojops_using_command debug' -a ci -d 'Diagnose CI/CD failures'
# Subcommands: analyze
complete -c dojops -n '__dojops_using_command analyze' -a diff -d 'Analyze infrastructure diff'
# Subcommands: agents
complete -c dojops -n '__dojops_using_command agents' -a list -d 'List agents'
complete -c dojops -n '__dojops_using_command agents' -a info -d 'Show agent details'
complete -c dojops -n '__dojops_using_command agents' -a create -d 'Create custom agent'
complete -c dojops -n '__dojops_using_command agents' -a remove -d 'Remove custom agent'
# Subcommands: history
complete -c dojops -n '__dojops_using_command history' -a list -d 'List history'
complete -c dojops -n '__dojops_using_command history' -a show -d 'Show detail'
complete -c dojops -n '__dojops_using_command history' -a verify -d 'Verify audit chain'
complete -c dojops -n '__dojops_using_command history' -a audit -d 'View audit entries'
complete -c dojops -n '__dojops_using_command history' -a repair -d 'Repair audit chain'
# Subcommands: modules
complete -c dojops -n '__dojops_using_command modules' -a list -d 'List modules'
complete -c dojops -n '__dojops_using_command modules' -a init -d 'Scaffold module'
complete -c dojops -n '__dojops_using_command modules' -a validate -d 'Validate module'
complete -c dojops -n '__dojops_using_command modules' -a publish -d 'Publish to Hub'
complete -c dojops -n '__dojops_using_command modules' -a install -d 'Install from Hub'
complete -c dojops -n '__dojops_using_command modules' -a search -d 'Search Hub'
complete -c dojops -n '__dojops_using_command modules' -a dev -d 'Live validation'
# Subcommands: tools (deprecated alias for modules)
complete -c dojops -n '__dojops_using_command tools' -a list -d 'List modules'
complete -c dojops -n '__dojops_using_command tools' -a init -d 'Scaffold module'
complete -c dojops -n '__dojops_using_command tools' -a validate -d 'Validate module'
complete -c dojops -n '__dojops_using_command tools' -a publish -d 'Publish to Hub'
complete -c dojops -n '__dojops_using_command tools' -a install -d 'Install from Hub'
complete -c dojops -n '__dojops_using_command tools' -a search -d 'Search Hub'
complete -c dojops -n '__dojops_using_command tools' -a dev -d 'Live validation'
# Subcommands: toolchain
complete -c dojops -n '__dojops_using_command toolchain' -a list -d 'List binaries'
complete -c dojops -n '__dojops_using_command toolchain' -a load -d 'Load versions'
complete -c dojops -n '__dojops_using_command toolchain' -a install -d 'Install tool'
complete -c dojops -n '__dojops_using_command toolchain' -a remove -d 'Remove tool'
complete -c dojops -n '__dojops_using_command toolchain' -a clean -d 'Clean cache'
# Subcommands: config
complete -c dojops -n '__dojops_using_command config' -a show -d 'Show config'
complete -c dojops -n '__dojops_using_command config' -a get -d 'Get value'
complete -c dojops -n '__dojops_using_command config' -a set -d 'Set value'
complete -c dojops -n '__dojops_using_command config' -a delete -d 'Delete value'
complete -c dojops -n '__dojops_using_command config' -a validate -d 'Validate'
complete -c dojops -n '__dojops_using_command config' -a reset -d 'Reset config'
complete -c dojops -n '__dojops_using_command config' -a profile -d 'Manage profiles'
# Subcommands: config profile (3-level)
complete -c dojops -n '__dojops_using_subcommand config profile' -a create -d 'Create profile'
complete -c dojops -n '__dojops_using_subcommand config profile' -a use -d 'Switch profile'
complete -c dojops -n '__dojops_using_subcommand config profile' -a delete -d 'Delete profile'
complete -c dojops -n '__dojops_using_subcommand config profile' -a list -d 'List profiles'
# Subcommands: auth
complete -c dojops -n '__dojops_using_command auth' -a login -d 'Authenticate'
complete -c dojops -n '__dojops_using_command auth' -a status -d 'Auth status'
complete -c dojops -n '__dojops_using_command auth' -a logout -d 'Remove credentials'
# Subcommands: serve
complete -c dojops -n '__dojops_using_command serve' -a credentials -d 'Generate API key'
# Subcommands: chat
complete -c dojops -n '__dojops_using_command chat' -a export -d 'Export sessions'
# Subcommands: inspect
complete -c dojops -n '__dojops_using_command inspect' -a config -d 'Inspect config'
complete -c dojops -n '__dojops_using_command inspect' -a session -d 'Inspect session'
# Subcommands: provider
complete -c dojops -n '__dojops_using_command provider' -a list -d 'List providers'
complete -c dojops -n '__dojops_using_command provider' -a default -d 'Set default'
complete -c dojops -n '__dojops_using_command provider' -a add -d 'Add provider'
complete -c dojops -n '__dojops_using_command provider' -a remove -d 'Remove provider'
complete -c dojops -n '__dojops_using_command provider' -a switch -d 'Switch provider'
# Subcommands: cron
complete -c dojops -n '__dojops_using_command cron' -a add -d 'Add job'
complete -c dojops -n '__dojops_using_command cron' -a list -d 'List jobs'
complete -c dojops -n '__dojops_using_command cron' -a remove -d 'Remove job'
# Subcommands: completion
complete -c dojops -n '__dojops_using_command completion' -a bash -d 'Bash completions'
complete -c dojops -n '__dojops_using_command completion' -a zsh -d 'Zsh completions'
complete -c dojops -n '__dojops_using_command completion' -a fish -d 'Fish completions'
complete -c dojops -n '__dojops_using_command completion' -a install -d 'Install completions'

# Global flags
complete -c dojops -l verbose -d 'Verbose output'
complete -c dojops -l debug -d 'Debug-level output'
complete -c dojops -l quiet -d 'Suppress non-essential output'
complete -c dojops -l no-color -d 'Disable color output'
complete -c dojops -l raw -d 'Raw output'
complete -c dojops -l non-interactive -d 'Disable interactive prompts'
complete -c dojops -l dry-run -d 'Preview changes'
complete -c dojops -l provider -d 'LLM provider' -x -a '(__dojops_complete_providers)'
complete -c dojops -l model -d 'LLM model' -x
complete -c dojops -l fallback-provider -d 'Fallback provider chain' -x
complete -c dojops -l agent -d 'Force specialist agent' -x -a '(__dojops_complete_agents)'
complete -c dojops -l module -d 'Force module' -x -a '(__dojops_complete_modules)'
complete -c dojops -l tool -d 'Force module (alias)' -x -a '(__dojops_complete_modules)'
complete -c dojops -l file -s f -d 'Read prompt from file' -r -F
complete -c dojops -l profile -d 'Config profile' -x
complete -c dojops -l temperature -d 'LLM temperature (0-2)' -x
complete -c dojops -l timeout -d 'Timeout in ms' -x
complete -c dojops -l output -d 'Output format' -x -a 'table json yaml'
complete -c dojops -s h -l help -d 'Show help'
complete -c dojops -s V -l version -d 'Show version'

# Command-specific flags: plan
complete -c dojops -n '__dojops_using_command plan' -l execute -d 'Execute with approval'
complete -c dojops -n '__dojops_using_command plan' -l yes -d 'Auto-approve'
complete -c dojops -n '__dojops_using_command plan' -l skip-verify -d 'Skip validation'
# Command-specific flags: apply
complete -c dojops -n '__dojops_using_command apply' -l resume -d 'Resume partial plan'
complete -c dojops -n '__dojops_using_command apply' -l yes -d 'Auto-approve'
complete -c dojops -n '__dojops_using_command apply' -l skip-verify -d 'Skip validation'
complete -c dojops -n '__dojops_using_command apply' -l force -d 'Skip git dirty check'
complete -c dojops -n '__dojops_using_command apply' -l allow-all-paths -d 'Bypass write allowlist'
complete -c dojops -n '__dojops_using_command apply' -l install-packages -d 'Run pkg install after'
complete -c dojops -n '__dojops_using_command apply' -l replay -d 'Deterministic mode'
complete -c dojops -n '__dojops_using_command apply' -l task -d 'Execute single task' -x
complete -c dojops -n '__dojops_using_command apply' -l timeout -d 'Per-task timeout (sec)' -x
complete -c dojops -n '__dojops_using_command apply' -l repair-attempts -d 'Max self-repair attempts' -x
# Command-specific flags: scan
complete -c dojops -n '__dojops_using_command scan' -l security -d 'Security scans only'
complete -c dojops -n '__dojops_using_command scan' -l deps -d 'Dependency scans only'
complete -c dojops -n '__dojops_using_command scan' -l iac -d 'IaC scans only'
complete -c dojops -n '__dojops_using_command scan' -l sbom -d 'Software Bill of Materials'
complete -c dojops -n '__dojops_using_command scan' -l license -d 'License compliance'
complete -c dojops -n '__dojops_using_command scan' -l fix -d 'Auto-remediate findings'
complete -c dojops -n '__dojops_using_command scan' -l compare -d 'Compare with previous'
complete -c dojops -n '__dojops_using_command scan' -l target -d 'Scan target dir' -r -F
complete -c dojops -n '__dojops_using_command scan' -l fail-on -d 'Exit code threshold' -x -a 'CRITICAL HIGH MEDIUM LOW'
# Command-specific flags: serve
complete -c dojops -n '__dojops_using_command serve' -l port -d 'Server port' -x
complete -c dojops -n '__dojops_using_command serve' -l no-auth -d 'Disable API key auth'
complete -c dojops -n '__dojops_using_command serve' -l tls-cert -d 'TLS certificate' -r -F
complete -c dojops -n '__dojops_using_command serve' -l tls-key -d 'TLS key' -r -F
# Command-specific flags: chat
complete -c dojops -n '__dojops_using_command chat' -l session -d 'Named session' -x
complete -c dojops -n '__dojops_using_command chat' -l resume -d 'Resume recent session'
complete -c dojops -n '__dojops_using_command chat' -l agent -d 'Pin to agent' -x -a '(__dojops_complete_agents)'
complete -c dojops -n '__dojops_using_command chat' -s m -l message -d 'Single message' -x
# Command-specific flags: auto
complete -c dojops -n '__dojops_using_command auto' -l skip-verify -d 'Skip validation'
complete -c dojops -n '__dojops_using_command auto' -l force -d 'Skip git dirty check'
complete -c dojops -n '__dojops_using_command auto' -l allow-all-paths -d 'Bypass write allowlist'
complete -c dojops -n '__dojops_using_command auto' -l repair-attempts -d 'Max repair attempts' -x
complete -c dojops -n '__dojops_using_command auto' -l commit -d 'Auto-commit changes'
`;
