/**
 * Format DojOps review JSON into a markdown PR comment.
 * Used by the composite GitHub Action (action.yml).
 */

const SEVERITY_ICONS = {
  critical: "🔴",
  high: "🟠",
  medium: "🟡",
  low: "🔵",
};

function formatComment(rawJson) {
  let review;
  try {
    review = typeof rawJson === "string" ? JSON.parse(rawJson) : rawJson;
  } catch {
    return "## DojOps Review\n\n⚠️ Could not parse review results.";
  }

  const lines = ["## 🔍 DojOps PR Review", ""];

  // Score
  if (review.score !== undefined) {
    lines.push(`**Maturity Score:** ${review.score}/100`, "");
  }

  // Findings table
  const findings = review.findings || [];
  if (findings.length === 0) {
    lines.push("✅ No issues found.", "");
  } else {
    lines.push("| Severity | File | Finding |", "| --- | --- | --- |");
    for (const f of findings) {
      const sev = (f.severity || "info").toLowerCase();
      const icon = SEVERITY_ICONS[sev] || "⚪";
      const file = f.file || "-";
      const msg = (f.message || f.description || "").replace(/\|/g, "\\|").replace(/\n/g, " ");
      lines.push(`| ${icon} ${sev} | \`${file}\` | ${msg} |`);
    }
    lines.push("");
  }

  // Summary counts
  const counts = {};
  for (const f of findings) {
    const sev = (f.severity || "info").toLowerCase();
    counts[sev] = (counts[sev] || 0) + 1;
  }
  if (Object.keys(counts).length > 0) {
    const summary = Object.entries(counts)
      .map(([sev, count]) => `${SEVERITY_ICONS[sev] || "⚪"} ${count} ${sev}`)
      .join(" · ");
    lines.push(`**Summary:** ${summary}`, "");
  }

  lines.push("---", "*Generated by [DojOps](https://dojops.ai)*");
  return lines.join("\n");
}

// eslint-disable-next-line no-undef
module.exports = { formatComment };
